config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post 'draw', to: 'home#draw'
  get 'my_page', to: 'home#my_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draw_idol.rb
class DrawIdol < ApplicationRecord
  belongs_to :user
  belongs_to :idol

  def self.create_from_idol!(idol, user)
    draw_idol = DrawIdol.new
    draw_idol.user_id = user.id
    draw_idol.idol_id = idol.id
    draw_idol.name = idol.name
    draw_idol.img_url = idol.img_url
    draw_idol.save!
    draw_idol
  end

end

app/models/ethereum_api.rb
class EthereumAPI
  require "json"

  # この設定は自分の環境に合わせる
  ETHEREUM_ADDRESS = "/Users/user1/data_testnet/geth.ipc"
  ETHEREUM_IDOL_CONTRACT = "#{Dir.pwd}/contracts/IdolContract.sol"
  CONTRACT_ADDRESS = "0x6db6c68c05c0b7d228ba5322d1beab5c2ac6924b"

  SUPPLIER_ADDRESS = "0x030ad335eb3154c720c1da0be92c295fc1fbe0ae"
  SUPPLIER_PASSWORD = "pass0"

  IDOL_ABI = '[{  "constant": true,  "inputs": [{  "name": "_id",  "type": "uint256"}  ],  "name": "getIdol",  "outputs": [{  "name": "",  "type": "string"},{  "name": "",  "type": "uint256"}  ],  "payable": false,  "stateMutability": "view",  "type": "function"},{  "constant": false,  "inputs": [{  "name": "_id",  "type": "uint256"},{  "name": "_userId",  "type": "uint256"}  ],  "name": "decreaseIssuance",  "outputs": [{  "name": "",  "type": "bytes32"}  ],  "payable": false,  "stateMutability": "nonpayable",  "type": "function"},{  "constant": true,  "inputs": [{  "name": "_idolKey",  "type": "bytes32"}  ],  "name": "getMappingIdolHashToOnwer",  "outputs": [{  "name": "",  "type": "uint256"}  ],  "payable": false,  "stateMutability": "view",  "type": "function"},{  "constant": true,  "inputs": [{  "name": "_id",  "type": "uint256"}  ],  "name": "checkIdolExistence",  "outputs": [{  "name": "",  "type": "bool"}  ],  "payable": false,  "stateMutability": "view",  "type": "function"},{  "constant": true,  "inputs": [],  "name": "id",  "outputs": [{  "name": "",  "type": "uint256"}  ],  "payable": false,  "stateMutability": "view",  "type": "function"},{  "constant": false,  "inputs": [{  "name": "_name",  "type": "string"},{  "name": "_issuance",  "type": "uint256"}  ],  "name": "setIdol",  "outputs": [],  "payable": false,  "stateMutability": "nonpayable",  "type": "function"},{  "constant": true,  "inputs": [],  "name": "developerAddress",  "outputs": [{  "name": "",  "type": "address"}  ],  "payable": false,  "stateMutability": "view",  "type": "function"},{  "constant": false,  "inputs": [],  "name": "setDeveloperAddress",  "outputs": [],  "payable": false,  "stateMutability": "nonpayable",  "type": "function"}  ]'

  # とりま、clientのアカウントはaccounts[0]で固定
  def set_client
    @client = Ethereum::IpcClient.new(ETHEREUM_ADDRESS)
    @client.personal_unlock_account(SUPPLIER_ADDRESS, SUPPLIER_PASSWORD)
  end

  def check_idol_issuance(idol_id, user)

    @client = Ethereum::IpcClient.new(ETHEREUM_ADDRESS)
    @client.personal_unlock_account(SUPPLIER_ADDRESS, SUPPLIER_PASSWORD)
    puts @client.eth_get_balance("0x030ad335eb3154c720c1da0be92c295fc1fbe0ae")
    begin
      @contract = Ethereum::Contract.create(file: ETHEREUM_IDOL_CONTRACT, client: @client, address: CONTRACT_ADDRESS, abi: IDOL_ABI)
      binding.pry
      result = @contract.call.check_idol_existence(idol_id)
    rescue => e
      puts "Exception handling"
      puts e.message
    end

    if result == true
      registered_id = @contract.transact_and_wait.decrease_issuance(idol_id, user.id)
      return result
    else
      return result
    end
  end
end

app/models/idol.rb
class Idol < ApplicationRecord
  # アイドルをランダムに1件返す
  def self.get_idol
    # TODO
    Idol.all.sample
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable, :validatable

  has_many :draw_idols
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  # アイドルくじを引く
  def draw
    @idol = Idol.get_idol
    smartContract = EthereumAPI.new()
    contract_result = smartContract.check_idol_issuance(@idol.id, current_user)

    if contract_result == true
      DrawIdol.create_from_idol!(@idol, current_user)
    else
      # TODO: idolの発行枚数が上限に達している場合
    end
  end

  def my_page
    @draw_idols = current_user.draw_idols
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/draw.html.erb
<h1 class = 'text-center'>
  <%= "GET! #{@idol.name}"%>
</h1>
<%= image_tag @idol.img_url, size: '500x500', class: 'img-responsive center-block'%>

app/views/home/index.html.erb
<%= form_tag('/draw', method: 'post') do %>
  <div class = 'text-center'>
    <%= submit_tag 'アイドルくじを引く' %>
  </div>
<% end %>

app/views/home/my_page.html.erb
<div class = 'row'>
  <% @draw_idols.each do |draw_idol| %>
  <div class = 'col-md-3'>
    <%= draw_idol.name %>
    <%= image_tag draw_idol.img_url, size: '100x100', class: '' %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealIdolMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav>
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %>
        <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
        <!-- *_path はUserモデルを作成したときに、
          deviseにより自動で作成されてますので、rake routesで確認できます -->
        <!--Logged in as <strong><%= current_user.email %></strong>.-->
        <!--<%= link_to 'プロフィール変更', edit_user_registration_path %> | -->
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> |
        <%= link_to "アイドルコレクション", my_page_path %>
      <% else %>
        <%= link_to "登録", new_user_registration_path %> |
        <%= link_to "ログイン", new_user_session_path %>
      <% end %>
    </nav>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>